import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { continueSelectedActiveExercise, recoverSelectedBrokenExercise, refreshActiveExerciseConflict, type ActiveExerciseConflictDetail } from "@/services/exercise/ActiveExerciseConflictResolutionService";

export default function ActiveExerciseConflictScreen(){
  const[items,setItems]=useState<readonly ActiveExerciseConflictDetail[]>([]);const[pending,setPending]=useState<string>();const[error,setError]=useState<string>();
  useEffect(()=>{let active=true;void refreshActiveExerciseConflict().then(result=>{if(active)setItems(result);});return()=>{active=false;};},[]);
  const resume=async(exerciseId:string)=>{setPending(exerciseId);setError(undefined);const result=await continueSelectedActiveExercise(exerciseId);setPending(undefined);if(!result.ok){setError(result.code);return;}router.replace("/excon/dashboard");};
  const recover=async(item:ActiveExerciseConflictDetail)=>{setPending(item.exerciseId);setError(undefined);const result=await recoverSelectedBrokenExercise(item.exerciseId,item.version);setPending(undefined);if(!result.ok){setError(result.message);return;}const remaining=await refreshActiveExerciseConflict();setItems(remaining);if(remaining.length<2)router.replace("/excon");};
  const confirmRecovery=(item:ActiveExerciseConflictDetail)=>Alert.alert("Kas lõpetada katkine õppus?",`${item.exerciseId} lõpetatakse auditeeritud taastamistöövooga. Kliinilist olekut ei fabritseerita.`,[{text:"Tühista",style:"cancel"},{text:"Lõpeta katkine õppus",style:"destructive",onPress:()=>void recover(item)}]);
  return <ScrollView contentContainerStyle={styles.container} testID="active-exercise-conflict-screen"><Text style={styles.title}>Aktiivsete õppuste konflikt</Text><Text style={styles.body}>Remote authoritative olekus on mitu aktiivset õppust. Runtime ei käivitu enne selgesõnalist valikut.</Text><Text style={styles.count}>Aktiivseid õppusi: {items.length}</Text>
    {items.map(item=><View key={item.exerciseId} style={styles.card} testID={`active-exercise-${item.exerciseId}`}><Text style={styles.cardTitle}>{item.packageId??"Õppus"}</Text><Text style={styles.meta}>{item.exerciseId}</Text><Text style={styles.meta}>{item.lifecycle} · T+{item.simulationTimeSec??0}s · versioon {item.version}</Text><Text style={styles.meta}>Uuendatud: {new Date(item.updatedAt).toLocaleString("et-EE")}</Text><Text style={styles.meta}>Kontrollpunkt: {item.checkpoint}{item.checkpointRevision!==undefined?` · rev ${item.checkpointRevision}`:""}</Text><Text style={styles.meta}>Writer lease: {item.lease}{item.writerInstanceId?` · ${item.writerInstanceId}`:""}</Text><Pressable disabled={Boolean(pending)} style={[styles.primary,pending&&styles.disabled]} onPress={()=>void resume(item.exerciseId)}><Text style={styles.buttonText}>{pending===item.exerciseId?"Kontrollin…":"Jätka seda õppust"}</Text></Pressable>{item.recoveryEligible&&<Pressable disabled={Boolean(pending)} style={[styles.danger,pending&&styles.disabled]} onPress={()=>confirmRecovery(item)}><Text style={styles.buttonText}>Lõpeta katkine õppus</Text></Pressable>}</View>)}
    {error&&<Text style={styles.error}>{error}</Text>}<Pressable style={styles.secondary} onPress={()=>void refreshActiveExerciseConflict().then(setItems)}><Text style={styles.secondaryText}>Värskenda nimekirja</Text></Pressable><Pressable style={styles.secondary} onPress={()=>router.replace("/excon")}><Text style={styles.secondaryText}>Tagasi EXCON-i vaatesse</Text></Pressable></ScrollView>;
}
const styles=StyleSheet.create({container:{padding:20,paddingBottom:40,backgroundColor:"#fff"},title:{fontSize:28,fontWeight:"900",color:"#172b4d"},body:{marginTop:8,color:"#42526e",lineHeight:21},count:{marginVertical:16,fontSize:18,fontWeight:"800"},card:{borderWidth:1,borderColor:"#d0d5dd",borderRadius:14,padding:14,marginBottom:12},cardTitle:{fontSize:18,fontWeight:"900",color:"#172b4d"},meta:{marginTop:5,color:"#475467"},primary:{backgroundColor:"#005bbb",borderRadius:10,padding:12,alignItems:"center",marginTop:12},danger:{backgroundColor:"#9b1c1c",borderRadius:10,padding:12,alignItems:"center",marginTop:8},buttonText:{color:"#fff",fontWeight:"900"},secondary:{borderWidth:2,borderColor:"#005bbb",borderRadius:10,padding:12,alignItems:"center",marginTop:10},secondaryText:{color:"#005bbb",fontWeight:"900"},disabled:{opacity:.5},error:{color:"#9b1c1c",fontWeight:"800",marginVertical:8}});
