import type { AnalyticsMetricProvider } from "@/models/analytics/Analytics";
import type { ExerciseTimelineEvent } from "@/models/exercise/ExerciseTimelineEvent";
import { reconstructDebrief } from "@/services/debrief/DebriefEngine";
import { generateAnalytics } from "../AnalyticsEngine";
import { AnalyticsProviderRegistry } from "../AnalyticsProviderRegistry";
import { DEFAULT_ANALYTICS_PRECISION } from "../AnalyticsPrecision";
import { ExerciseMetricsProvider } from "../providers/ExerciseMetricsProvider";
import { InterventionMetricsProvider } from "../providers/InterventionMetricsProvider";
import { OwnershipMetricsProvider } from "../providers/OwnershipMetricsProvider";
import { PatientFlowMetricsProvider } from "../providers/PatientFlowMetricsProvider";
import { ResourceMetricsProvider } from "../providers/ResourceMetricsProvider";
import { TimelineMetricsProvider } from "../providers/TimelineMetricsProvider";

const providers: readonly AnalyticsMetricProvider[] = [ExerciseMetricsProvider, PatientFlowMetricsProvider, OwnershipMetricsProvider, InterventionMetricsProvider, TimelineMetricsProvider, ResourceMetricsProvider];
const event = (id: string, time: number, type: string, category: ExerciseTimelineEvent["category"], patientId?: string, issuedBy?: string, metadata?: Readonly<Record<string, unknown>>): ExerciseTimelineEvent => Object.freeze({ id, exerciseId: "CORE", simulationTimeSec: time, sequenceNumber: Number(id.replace(/\D/g, "")) || 1, category, type, severity: "INFO", title: type, patientId, issuedBy, metadata });
const makeDebrief = (canonical = true, large = false) => reconstructDebrief({ exercise: { exerciseId: "CORE", lifecycleState: "COMPLETED", simulationTimeSec: large ? 10_000 : 120, speed: 1, version: 5, ...(canonical ? { clockVersion: 2 as const, clockInitializedAtSimulationTimeSec: 0 } : {}) }, patients: Array.from({ length: large ? 100 : 2 }, (_, index) => ({ patient: { id: `PT-${index + 1}`, name: `Patient ${index + 1}`, location: "EMO", status: index === 0 ? "Completed" as const : "Active" as const } })), timeline: large ? Array.from({ length: 10_000 }, (_, index) => event(`L-${index + 1}`, index, index % 7 === 0 ? "INTERVENTION" : "NOTE", "PATIENT", `PT-${index % 100 + 1}`)) : [
  event("E-1", 0, "ExerciseStarted", "EXERCISE", undefined, "Exercise Controller", { commandType: "START_EXERCISE", outcome: "ACCEPTED", resultingSpeed: 1 }), event("E-2", 5, "ASSIGNMENT", "AUDIT", "PT-1", "CM-1"), event("E-3", 10, "INTERVENTION", "PATIENT", "PT-1"), event("E-4", 12, "MEDICATION", "PATIENT", "PT-1"), event("E-5", 20, "ExercisePaused", "EXERCISE", undefined, "Exercise Controller", { commandType: "PAUSE_EXERCISE", outcome: "ACCEPTED" }), event("E-6", 30, "ExerciseResumed", "EXERCISE", undefined, "Exercise Controller", { commandType: "RESUME_EXERCISE", outcome: "ACCEPTED", resultingSpeed: 2 }), event("E-7", 35, "ASSIGNMENT", "AUDIT", "PT-1", "CM-2"), event("E-8", 40, "TRANSFER", "AUDIT", "PT-1", "CM-2"), event("E-9", 50, "ORDER", "PATIENT", "PT-1"), event("E-10", 60, "IMAGING", "PATIENT", "PT-1"), event("E-11", 70, "LAB", "PATIENT", "PT-1"), event("E-12", 120, "ExerciseCompleted", "EXERCISE", undefined, "Exercise Controller", { commandType: "COMPLETE_EXERCISE", outcome: "ACCEPTED" }), event("E-13", 15, "RESPIRATORY INTERVENTION", "PATIENT", "PT-2"),
] });
const analytics = (debrief: ReturnType<typeof makeDebrief>) => generateAnalytics(debrief, new AnalyticsProviderRegistry(providers), { precisionPolicy: DEFAULT_ANALYTICS_PRECISION });
const run = (canonical = true, large = false) => analytics(makeDebrief(canonical, large));

describe("WP-26 Core Metrics Pack", () => {
  it("registers six independent production providers with globally unique metrics", () => { const registry = new AnalyticsProviderRegistry(providers); expect(registry.providers).toHaveLength(6); expect(new Set(registry.definitions.map(item => item.metricId)).size).toBe(registry.definitions.length); });
  it("calculates factual exercise, patient, ownership, intervention and timeline metrics", () => { const report = run(); const metric = (id: string, subjectId?: string) => report.metrics.find(item => item.metricId === id && item.subjectId === subjectId); expect(metric("exercise.pause.count")).toMatchObject({ status: "VALUE", value: 1 }); expect(metric("exercise.paused_duration.seconds")).toMatchObject({ value: 10 }); expect(metric("patient.ownership.first_delay.seconds", "PT-1")).toMatchObject({ value: 5 }); expect(metric("patient.ownership.change_count", "PT-1")).toMatchObject({ value: 1 }); expect(metric("patient.transfer.count", "PT-1")).toMatchObject({ value: 1 }); expect(metric("patient.medication.count", "PT-1")).toMatchObject({ value: 1 }); expect(metric("patient.order.count", "PT-1")).toMatchObject({ value: 1 }); expect(metric("timeline.event.count")).toMatchObject({ value: 13 }); expect(report.metrics.every(item => item.evidence.length > 0)).toBe(true); });
  it("uses explicit unavailable and not-applicable statuses for unsupported facts", () => { const report = run(); expect(report.metrics.find(item => item.metricId === "ownership.conflict.count")).toMatchObject({ status: "UNAVAILABLE", reasonCode: "OWNERSHIP_INTERVALS_NOT_AVAILABLE" }); expect(report.metrics.filter(item => item.providerId === "core.resources").every(item => item.status === "NOT_APPLICABLE")).toBe(true); expect(report.metrics.find(item => item.metricId === "patient.ownership.first_delay.seconds" && item.subjectId === "PT-2")).toMatchObject({ status: "UNAVAILABLE", reasonCode: "MISSING_OWNERSHIP_HISTORY" }); });
  it("makes every duration-dependent metric unavailable for a legacy clock while preserving counts", () => { const report = run(false); expect(report.metrics.filter(item => item.unit === "SECONDS" || item.metricId.includes("per_minute")).every(item => item.status === "UNAVAILABLE")).toBe(true); expect(report.metrics.find(item => item.metricId === "timeline.event.count")).toMatchObject({ status: "VALUE", value: 13 }); });
  it("is deterministic including evidence and analytics hash", () => { const first = run(); const second = run(); expect(second).toEqual(first); expect(second.analyticsHash).toBe(first.analyticsHash); });
  it("supports 100 patients, 10k timeline events and over 1000 results", () => { const source = makeDebrief(true, true); const started = Date.now(); const report = analytics(source); expect(report.metrics.length).toBeGreaterThan(1000); expect(Date.now() - started).toBeLessThan(2_000); });
});
