import type { MetricResult } from "@/models/analytics/Analytics";
import { Pressable, StyleSheet, Text, View } from "react-native";
const read = (metrics: readonly MetricResult[], id: string, subjectId?: string) => metrics.find(metric => metric.metricId === id && metric.subjectId === subjectId);
const display = (metric?: MetricResult) => !metric ? "—" : metric.status !== "VALUE" ? metric.status.replaceAll("_", " ") : metric.unit === "RATIO" ? `${Math.round(Number(metric.value) * 100)}%` : String(metric.value);
export function AssessmentMetricsSummary({ metrics, patientId, onOpenAssessment }: { metrics: readonly MetricResult[]; patientId?: string; onOpenAssessment?: () => void }) {
  const id = (key: string) => patientId ? `patient.assessment.${key}` : key.endsWith("ratio") ? `assessment.${key}` : `assessment.expectations.${key}`; const total = read(metrics, id("total"), patientId); if (!total) return null; const applicable = read(metrics, id("applicable"), patientId); const assessable = read(metrics, id("assessable"), patientId);
  const items = [["Expectations", total], ["Applicable", applicable], ["Assessable", assessable], ["MET", read(metrics, id("met"), patientId)], ["NOT MET", read(metrics, id("not_met"), patientId)], ["Unavailable", read(metrics, id("unavailable"), patientId)], ["Not applicable", read(metrics, id("not_applicable"), patientId)], ["Assessment completion", read(metrics, id("completion_ratio"), patientId)], ["Expectation satisfaction", read(metrics, id("satisfaction_ratio"), patientId)]] as const;
  return <View style={styles.card}><Text style={styles.title}>Assessment Metrics{patientId ? ` · ${patientId}` : ""}</Text><Text style={styles.note}>Neutral descriptive aggregates</Text><View style={styles.grid}>{items.map(([label, metric]) => <View key={label} style={styles.item}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{display(metric)}</Text></View>)}</View>{assessable?.status === "VALUE" && applicable?.status === "VALUE" && <Text style={styles.basis}>Assessable {assessable.value} / {applicable.value} applicable</Text>}{onOpenAssessment && <Pressable onPress={onOpenAssessment} style={styles.button}><Text style={styles.buttonText}>Open contributing assessment results</Text></Pressable>}</View>;
}
const styles = StyleSheet.create({ card: { backgroundColor: "#f4f6f8", borderRadius: 12, padding: 14, marginBottom: 12 }, title: { color: "#172b4d", fontWeight: "900", fontSize: 19 }, note: { color: "#6b778c", marginTop: 2, fontSize: 12 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 }, item: { backgroundColor: "#fff", borderRadius: 8, padding: 9, minWidth: 120, flexGrow: 1 }, label: { color: "#6b778c", fontSize: 11, fontWeight: "700" }, value: { color: "#172b4d", fontSize: 19, fontWeight: "900", marginTop: 2 }, basis: { color: "#42526e", fontWeight: "700", marginTop: 10 }, button: { borderWidth: 1, borderColor: "#005bbb", borderRadius: 8, padding: 9, alignItems: "center", marginTop: 10 }, buttonText: { color: "#005bbb", fontWeight: "800" } });
