/* Generated by scripts/imaging-author.mjs. Do not edit by hand. */
import type { ImagingAuthoredPackageRecipe } from "./ImagingAuthoredPackageLoader";
import { deepFreeze } from "@/utils/immutable";

export const GENERATED_IMAGING_AUTHORED_PACKAGE_RECIPES = deepFreeze([
] satisfies readonly ImagingAuthoredPackageRecipe[]);
