/* Generated by scripts/imaging-asset-ingest.mjs. Do not edit by hand. */
import type { ImageSourcePropType } from "react-native";
import type { ImagingAssetReference } from "@/models/ImagingAsset";
import { deepFreeze } from "@/utils/immutable";

export const GENERATED_BUNDLED_IMAGING_ASSETS = deepFreeze([
  {
    assetId: "demo.head-ct.image01.v1",
    sourceKind: "BUNDLED_LOCAL" as const,
    resolverKey: "image01.jpg",
    sha256: "ae38226a9d0d803fcdfcc4b3bbcc3003a9e3b5ac7ffacc5378d6d18a7ef072b4",
    mediaType: "image/jpeg",
    byteLength: 71145,
    width: 606,
    height: 606,
    role: "PRIMARY_DIAGNOSTIC_IMAGE" as const,
    packageId: "russicaptor.demo",
    packageVersion: "1.0.0",
    patientId: "PT-001",
    definitionId: "IMG-001",
  },
] satisfies readonly ImagingAssetReference[]);

export const GENERATED_BUNDLED_IMAGING_SOURCES: Readonly<Record<string, ImageSourcePropType>> = Object.freeze({
  "image01.jpg": require("../../../assets/imaging/image01.jpg"),
});
