import type { ExerciseTimelineEvent } from "@/models/exercise/ExerciseTimelineEvent";
import type { DebriefReport } from "@/services/debrief/DebriefModel";
import { ALS_GENERIC_V1 } from "@/services/protocol/ReferenceProtocolConfigurations";
import { createProtocolConfiguration } from "@/services/protocol/ProtocolConfigurationHash";
import { assessProtocol } from "../ProtocolAssessmentEngine";
import { filterProtocolAssessment } from "../ProtocolAssessmentSelectors";

const event = (id: string, type: string, time: number, metadata: Record<string, unknown> = {}, patientId = "PT-001", sequenceNumber = time): ExerciseTimelineEvent => Object.freeze({ id, exerciseId: "EX-38", simulationTimeSec: time, sequenceNumber, category: "PATIENT", type, severity: "INFO", patientId, title: type.replaceAll("_", " "), metadata: Object.freeze(metadata) });
const debrief = (timeline: readonly ExerciseTimelineEvent[], clockMigrationStatus: DebriefReport["clockMigrationStatus"] = "CANONICAL"): DebriefReport => Object.freeze({ schemaVersion: "1.0", exerciseId: "EX-38", generatedFromReplayHash: "replay", simulationDurationSec: 120, patientCount: 1, completedPatients: 0, exerciseState: "RUNNING", commandCount: 0, auditCount: 0, timelineLength: timeline.length, patients: Object.freeze([{ patientId: "PT-001", name: "Patient", initialLocation: "Resus", finalLocation: "Resus", assignedCaseManagers: [], processes: [], interventions: [], medications: [], orders: [], imaging: [], labs: [], timelineEventIds: timeline.map(item => item.id), outcome: "STILL_ACTIVE" as const }]), timeline, generatedAtSimulationTime: 120, clockMigrationStatus, clockDiagnostics: [] });
const run = (timeline: readonly ExerciseTimelineEvent[], protocol = ALS_GENERIC_V1, clock?: DebriefReport["clockMigrationStatus"]) => assessProtocol({ protocol, debrief: debrief(timeline, clock), timeline });

describe("WP-38 Protocol Assessment Foundation", () => {
  test("evaluates ALS CPR and defibrillation expectations from canonical evidence", () => {
    const timeline = Object.freeze([event("A", "CARDIAC_ARREST_STARTED", 10, { cardiacState: "ARREST" }), event("C", "CPR_STARTED", 12), event("R", "CARDIAC_RHYTHM_OBSERVED", 20, { rhythm: "VF", rhythmClassification: "SHOCKABLE" }), event("D", "DEFIBRILLATION_ATTEMPTED", 25), event("RT", "CARDIAC_RHYTHM_TRANSITION", 26, { fromRhythm: "VF", toRhythm: "PERFUSING" })]);
    const report = run(timeline); expect(report.results.map(item => [item.expectationId, item.status])).toEqual([["EXPECT-CPR", "MET"], ["EXPECT-SHOCK", "MET"]]); expect(report.results[0].evidence.map(item => item.sourceId)).toEqual(["A", "C"]); expect(Object.isFrozen(report)).toBe(true); expect(Object.isFrozen(report.results)).toBe(true);
  });
  test("keeps NOT_MET, NOT_APPLICABLE and UNAVAILABLE semantically distinct", () => {
    expect(run([event("A", "CARDIAC_ARREST_STARTED", 10, { cardiacState: "ARREST" })]).results.find(item => item.expectationId === "EXPECT-CPR")?.status).toBe("NOT_MET");
    expect(run([event("P", "CARDIAC_STATE_CHANGED", 10, { cardiacState: "PERFUSING" })]).results.find(item => item.expectationId === "EXPECT-CPR")?.status).toBe("NOT_APPLICABLE");
    expect(run([]).results.find(item => item.expectationId === "EXPECT-CPR")?.status).toBe("UNAVAILABLE");
  });
  test("uses canonical time for AFTER, BEFORE and inclusive WITHIN matching", () => {
    const make = (relation: "AFTER" | "BEFORE" | "WITHIN", durationSec?: number) => createProtocolConfiguration({ ...ALS_GENERIC_V1, protocolId: `TEST_${relation}`, version: "1.0.0", rules: [], assessmentExpectations: [{ ...ALS_GENERIC_V1.assessmentExpectations[0], expectationId: "TEMP", temporalConstraint: { relation, durationSec } }] });
    expect(run([event("T", "CARDIAC_ARREST_STARTED", 10, { cardiacState: "ARREST" }), event("A", "CPR_STARTED", 15)], make("AFTER")).results[0].status).toBe("MET");
    expect(run([event("A", "CPR_STARTED", 5), event("T", "CARDIAC_ARREST_STARTED", 10, { cardiacState: "ARREST" })], make("BEFORE")).results[0].status).toBe("MET");
    expect(run([event("T", "CARDIAC_ARREST_STARTED", 10, { cardiacState: "ARREST" }), event("A", "CPR_STARTED", 15)], make("WITHIN", 5)).results[0].status).toBe("MET");
  });
  test("uses earliest trigger/action and stable sequence tie-break", () => {
    const report = run([event("T2", "CARDIAC_ARREST_STARTED", 10, { cardiacState: "ARREST" }, "PT-001", 2), event("T1", "CARDIAC_ARREST_STARTED", 10, { cardiacState: "ARREST" }, "PT-001", 1), event("A2", "CPR_STARTED", 12, {}, "PT-001", 4), event("A1", "CPR_STARTED", 12, {}, "PT-001", 3)]);
    expect(report.results.find(item => item.expectationId === "EXPECT-CPR")?.evidence.map(item => item.sourceId)).toEqual(["T1", "A1"]);
  });
  test("returns UNAVAILABLE for temporal conclusions on a legacy clock", () => { const report = run([event("T", "CARDIAC_ARREST_STARTED", 10, { cardiacState: "ARREST" }), event("A", "CPR_STARTED", 12)], ALS_GENERIC_V1, "MIGRATION_AVAILABLE"); expect(report.results[0]).toMatchObject({ status: "UNAVAILABLE", diagnostics: [{ code: "LEGACY_CLOCK" }] }); });
  test("isolates malformed expectations", () => { const protocol = createProtocolConfiguration({ ...ALS_GENERIC_V1, protocolId: "MALFORMED_TEST", version: "1.0.0", rules: [], assessmentExpectations: [{ ...ALS_GENERIC_V1.assessmentExpectations[0], expectationId: "BAD", temporalConstraint: { relation: "REPEATING", durationSec: 10 } }, ALS_GENERIC_V1.assessmentExpectations[1]] }); const report = run([event("R", "CARDIAC_RHYTHM_OBSERVED", 1, { rhythmClassification: "SHOCKABLE" }), event("D", "DEFIBRILLATION_ATTEMPTED", 2), event("T", "CARDIAC_RHYTHM_TRANSITION", 3)], protocol); expect(report.results.find(item => item.expectationId === "BAD")?.status).toBe("UNAVAILABLE"); expect(report.results.find(item => item.expectationId === "EXPECT-SHOCK")?.status).toBe("MET"); });
  test("is deterministic and canonical matching ignores source insertion order", () => { const values = [event("A", "CARDIAC_ARREST_STARTED", 1, { cardiacState: "ARREST" }), event("C", "CPR_STARTED", 2)]; const one = run(values); const replay = run(values); const reordered = run([...values].reverse()); expect(replay).toEqual(one); expect(one.assessmentHash).toBe(replay.assessmentHash); expect(reordered.results).toEqual(one.results); expect(filterProtocolAssessment(one, { status: "MET", patientId: "PT-001", expectationId: "EXPECT-CPR" })).toHaveLength(1); });
  test("indexes a 10,000-event timeline and evaluates 500 expectations", () => { const expectations = Array.from({ length: 500 }, (_, index) => ({ ...ALS_GENERIC_V1.assessmentExpectations[0], expectationId: `EXPECT-${String(index).padStart(3, "0")}` })); const protocol = createProtocolConfiguration({ ...ALS_GENERIC_V1, protocolId: "LOAD_TEST", version: "1.0.0", rules: [], assessmentExpectations: expectations }); const timeline = Array.from({ length: 10_000 }, (_, index) => index === 0 ? event("TRIGGER", "CARDIAC_ARREST_STARTED", 0, { cardiacState: "ARREST" }, "PT-001", 1) : index === 1 ? event("ACTION", "CPR_STARTED", 1, {}, "PT-001", 2) : event(`E-${index}`, "NOTE", index, {}, "PT-001", index + 1)); const started = Date.now(); const report = run(timeline, protocol); expect(report.results).toHaveLength(500); expect(report.results.every(item => item.status === "MET")).toBe(true); expect(Date.now() - started).toBeLessThan(5000); });
});
