import { useState, useSyncExternalStore } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { createPatientTransportCommandId, getPatientTransportSnapshot, getPatientTransportVersion, startPatientTransport, subscribeToPatientTransport } from "@/services/runtime/exercise/PatientTransportRuntimeService";

export function PatientTransportControls({patientId,readOnly=false}:{patientId:string;readOnly?:boolean}) {
  useSyncExternalStore(subscribeToPatientTransport,getPatientTransportVersion,getPatientTransportVersion); const snapshot=getPatientTransportSnapshot(); const [feedback,setFeedback]=useState("");
  if(!snapshot)return null; const current=snapshot.transports.find(item=>item.patientId===patientId && !["COMPLETED","CANCELLED","FAILED"].includes(item.state)); const resource=snapshot.resources[0];
  return <View style={styles.card}><Text style={styles.title}>Transport</Text><Text style={styles.text}>Asukoht: {snapshot.patientLocations[patientId] ?? "–"}</Text><Text style={styles.text}>{resource.resourceId}: {resource.state}</Text>{current&&<Text style={styles.active}>Transpordil: {current.destinationId} · {current.state}</Text>}{!readOnly&&!current&&snapshot.configuration.destinations.map(destination=><Pressable key={destination.destinationId} style={styles.button} onPress={()=>{const result=startPatientTransport(createPatientTransportCommandId(patientId),patientId,resource.resourceId,destination.destinationId);setFeedback(result.reason==="TRANSPORT_RESOURCE_BUSY"?"Reanimobiil on hõivatud":result.status==="STARTED"?"Transport algas":"Transporti ei saanud alustada");}}><Text style={styles.buttonText}>Alusta transporti: {destination.displayName}</Text></Pressable>)}{!!feedback&&<Text style={styles.feedback}>{feedback}</Text>}</View>;
}
const styles=StyleSheet.create({card:{backgroundColor:"#eef4ff",borderColor:"#84adff",borderWidth:1,borderRadius:12,padding:14,marginBottom:14,gap:7},title:{fontSize:18,fontWeight:"700"},text:{color:"#344054"},active:{color:"#175cd3",fontWeight:"700"},button:{backgroundColor:"#175cd3",padding:12,borderRadius:9},buttonText:{color:"white",fontWeight:"700",textAlign:"center"},feedback:{fontWeight:"600",color:"#344054"}});
