/* Generated by scripts/builder-compile.mjs. Do not edit by hand. */
import type { ExercisePackage } from "@/models/exercise/ExercisePackage";
import type { PackagePatientDataset } from "@/models/exercise/PackagePatientDataset";

export const GENERATED_BUILDER_PACKAGES: readonly ExercisePackage[] = [];
export const GENERATED_BUILDER_DATASETS: readonly PackagePatientDataset[] = [];
