import { AnalyticsSummaryCard } from "@/components/excon/analytics/AnalyticsSummaryCard";
import { MetricCard } from "@/components/excon/analytics/MetricCard";
import type { AnalyticsCategory, MetricScope, MetricStatus } from "@/models/analytics/Analytics";
import { getAnalyticsMetricDefinitions, getAnalyticsReport, getAnalyticsVersion, subscribeToAnalytics } from "@/services/AnalyticsService";
import { filterAnalyticsMetrics } from "@/services/analytics/AnalyticsSelectors";
import { router } from "expo-router";
import { useMemo, useState, useSyncExternalStore } from "react";
import { FlatList, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { analyticsCategoryLabel, analyticsMetricNameLabel, metricScopeLabel } from "@/localization/dataDrivenEt";
import { assessmentStatusLabel } from "@/localization/et";

export default function AnalyticsScreen() {
  useSyncExternalStore(subscribeToAnalytics, getAnalyticsVersion, getAnalyticsVersion); const report = getAnalyticsReport();
  const [category, setCategory] = useState<AnalyticsCategory>(); const [scope, setScope] = useState<MetricScope>(); const [status, setStatus] = useState<MetricStatus>(); const [providerId, setProviderId] = useState<string>(); const [patientId, setPatientId] = useState<string>(); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<string>();
  const metrics = useMemo(() => filterAnalyticsMetrics(report, { category, scope, status, providerId, patientId, search }), [report, category, scope, status, providerId, patientId, search]);
  const definitions = getAnalyticsMetricDefinitions(); const categories = [...new Set(report.metrics.map(metric => metric.category))]; const scopes = [...new Set(report.metrics.map(metric => metric.scope))]; const statuses = [...new Set(report.metrics.map(metric => metric.status))]; const providers = [...new Set(report.metrics.map(metric => metric.providerId))]; const patients = [...new Set(report.metrics.flatMap(metric => [metric.subjectId, ...metric.evidence.map(item => item.patientId)].filter((value): value is string => Boolean(value))))];
  return <FlatList data={metrics} keyExtractor={metric => `${metric.providerId}:${metric.metricId}:${metric.subjectId ?? ""}`} contentContainerStyle={styles.container}
    ListHeaderComponent={<View><View style={styles.top}><View><Text style={styles.title}>Analüütika</Text><Text style={styles.subtitle}>Kirjutuskaitstud kanooniliste mõõdikute vaade</Text></View><Pressable onPress={() => router.back()}><Text style={styles.back}>Tagasi</Text></Pressable></View><AnalyticsSummaryCard report={report} />
      <TextInput style={styles.input} placeholder="Otsi mõõdikuid" value={search} onChangeText={setSearch} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>
        {categories.map(value => <Chip key={value} label={analyticsCategoryLabel(value)} active={category === value} onPress={() => setCategory(current => current === value ? undefined : value)} />)}
        {scopes.map(value => <Chip key={value} label={metricScopeLabel(value)} active={scope === value} onPress={() => setScope(current => current === value ? undefined : value)} />)}
        {statuses.map(value => <Chip key={value} label={assessmentStatusLabel(value)} active={status === value} onPress={() => setStatus(current => current === value ? undefined : value)} />)}
        {providers.map(value => <Chip key={value} label={value} active={providerId === value} onPress={() => setProviderId(current => current === value ? undefined : value)} />)}
        {patients.map(value => <Chip key={value} label={value} active={patientId === value} onPress={() => setPatientId(current => current === value ? undefined : value)} />)}
      </ScrollView>{report.diagnostics.length > 0 && <View style={styles.diagnostics}><Text style={styles.diagnosticTitle}>Diagnostika</Text>{report.diagnostics.map((item, index) => <Text key={`${item.code}:${item.providerId}:${item.metricId}:${index}`} style={styles.diagnostic}>• {item.code}: {item.message}</Text>)}</View>}<Text style={styles.count}>{metrics.length} mõõdikut</Text></View>}
    renderItem={({ item }) => { const definition = definitions.find(candidate => candidate.metricId === item.metricId); return <MetricCard metric={item} name={analyticsMetricNameLabel(item.metricId, definition?.name ?? item.metricId)} selected={selected === item.metricId} onPress={() => setSelected(current => current === item.metricId ? undefined : item.metricId)} onEvidencePress={assessmentId => router.push({ pathname: "/excon/assessment", params: { assessmentId } })} />; }} ListEmptyComponent={<Text style={styles.empty}>Filtritele vastavaid mõõdikuid ei leitud.</Text>} />;
}
function Chip({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable style={[styles.chip, active && styles.chipActive]} onPress={onPress}><Text style={[styles.chipText, active && styles.chipTextActive]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ container: { flexGrow: 1, backgroundColor: "#fff", padding: 18, paddingBottom: 40 }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }, title: { fontSize: 28, fontWeight: "900", color: "#172b4d" }, subtitle: { color: "#5e6c84", marginTop: 3 }, back: { color: "#005bbb", fontWeight: "800" }, input: { borderWidth: 1, borderColor: "#c1c7d0", borderRadius: 9, padding: 10, marginBottom: 8 }, filters: { gap: 6, paddingBottom: 10 }, chip: { borderWidth: 1, borderColor: "#c1c7d0", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7 }, chipActive: { backgroundColor: "#172b4d" }, chipText: { color: "#42526e", fontSize: 11, fontWeight: "800" }, chipTextActive: { color: "#fff" }, diagnostics: { backgroundColor: "#fff3cd", borderRadius: 9, padding: 10, marginBottom: 9 }, diagnosticTitle: { color: "#7a5700", fontWeight: "900" }, diagnostic: { color: "#7a5700", marginTop: 3, fontSize: 12 }, count: { color: "#6b778c", fontWeight: "800", marginBottom: 8 }, empty: { textAlign: "center", color: "#6b778c", padding: 24 } });
