import type { CanonicalExerciseSnapshot } from "@/models/exercise/CanonicalExerciseSnapshot";
import { getPrepareNewExercisePresentation } from "@/components/excon/PrepareNewExerciseCard";
import { ALS_PROTOCOL_REFERENCE_EXERCISE_PACKAGE } from "../CanonicalExercisePackages";
import { ExercisePreparationService, type ExercisePreparationCommand } from "../ExercisePreparationService";
import { exercisePackageLoader, getExercisePackage } from "../ExercisePackageService";
import { PatientDatasetError } from "../PackagePatientMaterializationService";

const command: ExercisePreparationCommand = Object.freeze({ commandId: "PREPARE-1", currentExerciseId: "EX-A", newExerciseId: "EX-B", expectedVersion: 7, issuedBy: "Exercise Controller" });
const completed = (state: CanonicalExerciseSnapshot["lifecycleState"] = "COMPLETED"): CanonicalExerciseSnapshot => ({ exerciseId: "EX-A", lifecycleState: state, simulationTimeSec: 90, speed: 1, version: 7, clockVersion: 2, clockInitializedAtSimulationTimeSec: 0 });
const history = { exerciseId: "EX-A", snapshot: completed(), debrief: {} as never, analytics: {} as never };
function setup(options: { state?: CanonicalExerciseSnapshot["lifecycleState"]; active?: boolean; compatible?: boolean; bindFailure?: boolean; captureFailure?: boolean; resetFailure?: boolean; planFailure?: boolean } = {}) {
  let snapshot = completed(options.state); let resetCalls = 0; let archives = 0; let clears = 0; let publishes = 0; let unbinds = 0; let bindings = 0; let installs = 0;
  const service = new ExercisePreparationService({ snapshot: () => snapshot, activePackage: () => options.active === false ? undefined : ALS_PROTOCOL_REFERENCE_EXERCISE_PACKAGE,
    compatibility: () => options.compatible === false ? "INCOMPATIBLE" : "SUPPORTED",
    bind: () => { bindings += 1; if (options.bindFailure) throw new Error("CLINICAL_MODULE_COMPOSITION_FAILED"); return ALS_PROTOCOL_REFERENCE_EXERCISE_PACKAGE; },
    unbind: () => { unbinds += 1; }, capture: () => { if (options.captureFailure) throw new Error("archive unavailable"); return history; }, archive: value => { archives += 1; return value; }, clear: () => { clears += 1; }, publish: () => { publishes += 1; },
    plan: (exerciseId, pkg) => { if (options.planFailure) throw new PatientDatasetError("MALFORMED_PATIENT", "invalid dataset"); return { exerciseId, packageId: pkg.packageId, packageVersion: pkg.packageVersion, packageHash: pkg.packageHash, datasetId: pkg.patientDatasetId, datasetVersion: "1", materializationHash: "hash", patients: [] }; }, install: () => { installs += 1; },
    reset: () => { resetCalls += 1; if (options.resetFailure) return { ok: false as const, snapshot, audit: { commandId: command.commandId, priorExerciseId: "EX-A", newExerciseId: "EX-B", simulationTimeSec: 90, outcome: "REJECTED" as const, reasonCode: "VERSION_CONFLICT" as const } }; snapshot = { exerciseId: "EX-B", lifecycleState: "READY", simulationTimeSec: 0, speed: 1, version: 8, clockVersion: 2, clockInitializedAtSimulationTimeSec: 0 }; return { ok: true as const, snapshot, archivedSnapshot: completed(), audit: { commandId: command.commandId, priorExerciseId: "EX-A", newExerciseId: "EX-B", simulationTimeSec: 90, outcome: "ACCEPTED" as const } }; },
  });
  return { service, counters: () => ({ resetCalls, archives, clears, publishes, unbinds, bindings, installs }), snapshot: () => snapshot };
}

describe("WP-39A Exercise Preparation", () => {
  test("prepares exactly one READY exercise from a completed exercise and keeps Start separate", () => { const subject = setup(); const result = subject.service.prepare(command); expect(result).toMatchObject({ ok: true, exerciseId: "EX-B" }); expect(subject.snapshot()).toMatchObject({ exerciseId: "EX-B", lifecycleState: "READY", simulationTimeSec: 0 }); expect(subject.counters()).toEqual({ resetCalls: 1, archives: 1, clears: 1, publishes: 1, unbinds: 0, bindings: 1, installs: 1 }); });
  test.each(["RUNNING", "PAUSED"] as const)("rejects replacement while %s", state => { const subject = setup({ state }); expect(subject.service.prepare(command)).toMatchObject({ ok: false, code: "ACTIVE_EXERCISE" }); expect(subject.counters().resetCalls).toBe(0); });
  test("rejects READY, missing and incompatible package states with typed diagnostics", () => { expect(setup({ state: "READY" }).service.prepare(command)).toMatchObject({ code: "INVALID_EXERCISE_STATE" }); expect(setup({ active: false }).service.prepare(command)).toMatchObject({ code: "NO_ACTIVE_PACKAGE" }); expect(setup({ compatible: false }).service.prepare(command)).toMatchObject({ code: "PACKAGE_INCOMPATIBLE" }); });
  test("is idempotent for the same command", () => { const subject = setup(); const first = subject.service.prepare(command); expect(subject.service.prepare(command)).toBe(first); expect(subject.counters().resetCalls).toBe(1); });
  test("does not publish partial READY state after binding or reset failure", () => { const binding = setup({ bindFailure: true }); expect(binding.service.prepare(command)).toMatchObject({ code: "MODULE_COMPOSITION_FAILED" }); expect(binding.counters()).toMatchObject({ resetCalls: 0, archives: 0, clears: 0, publishes: 0 }); const reset = setup({ resetFailure: true }); expect(reset.service.prepare(command)).toMatchObject({ code: "VERSION_CONFLICT" }); expect(reset.counters()).toMatchObject({ archives: 0, clears: 0, publishes: 0, unbinds: 1 }); });
  test("reports archive capture failures without binding or resetting", () => { const subject = setup({ captureFailure: true }); expect(subject.service.prepare(command)).toMatchObject({ code: "PERSISTENCE_FAILURE" }); expect(subject.counters()).toMatchObject({ bindings: 0, resetCalls: 0, archives: 0, publishes: 0 }); });
  test("validates the complete patient plan before capture, binding, reset or publication", () => { const subject = setup({ planFailure: true }); expect(subject.service.prepare(command)).toMatchObject({ code: "PATIENT_DATASET_INVALID" }); expect(subject.counters()).toEqual({ resetCalls: 0, archives: 0, clears: 0, publishes: 0, unbinds: 0, bindings: 0, installs: 0 }); });
  test("binds exact ALS protocol and deterministic clinical module provenance through Package Loader", () => { const id = "WP39A-BINDING"; exercisePackageLoader.bind(id, ALS_PROTOCOL_REFERENCE_EXERCISE_PACKAGE); const bound = getExercisePackage(id); expect(bound).toMatchObject({ packageId: "russicaptor.als-protocol-reference", packageVersion: "1.0.0", definition: { protocolProvenance: { protocolId: "ALS_GENERIC_V1", version: "1.0.0" } } }); expect(bound.definition.clinicalModuleComposition?.modules.map(item => `${item.moduleId}@${item.version}`)).toEqual(["AIRWAY_V1@1.0.0", "CARDIAC_ARREST_V1@1.0.0", "MEDICATION_CORE_V1@1.0.0", "ALS_V1@1.0.0"]); exercisePackageLoader.unbind(id); });
  test("exposes preparation UI only in COMPLETED state and guides missing package", () => { expect(getPrepareNewExercisePresentation("RUNNING", true, false).visible).toBe(false); expect(getPrepareNewExercisePresentation("COMPLETED", false, false)).toMatchObject({ visible: true, showCatalogGuidance: true, enabled: false }); expect(getPrepareNewExercisePresentation("COMPLETED", true, false)).toMatchObject({ enabled: true, label: "Valmista uus õppus" }); expect(getPrepareNewExercisePresentation("COMPLETED", true, true)).toMatchObject({ enabled: false, label: "Valmistan…" }); });
});
