import type { AnalyticsEvaluationContext, AnalyticsMetricProvider, MetricResult } from "@/models/analytics/Analytics";
import { coreMetricIndex, definition, eventEvidence, evidence, legacyDuration, unavailableResult, valueResult } from "./CoreMetricsSupport";
const id = "core.ownership"; const defs = Object.freeze([
  definition(id, "ownership.duration.average.seconds", "Average ownership duration", "Average observed ownership interval", "OWNERSHIP", "SECONDS", "EXERCISE"), definition(id, "ownership.duration.longest.seconds", "Longest ownership duration", "Longest observed ownership interval", "OWNERSHIP", "SECONDS", "EXERCISE"), definition(id, "ownership.duration.shortest.seconds", "Shortest ownership duration", "Shortest observed ownership interval", "OWNERSHIP", "SECONDS", "EXERCISE"), definition(id, "ownership.handover.count", "Ownership handovers", "Patient ownership handovers", "OWNERSHIP", "COUNT", "EXERCISE"), definition(id, "ownership.patient_without_owner.count", "Patients without owner", "Patients with no recorded Case Manager", "OWNERSHIP", "COUNT", "EXERCISE"), definition(id, "ownership.conflict.count", "Multiple ownership conflicts", "Overlapping canonical ownership intervals", "OWNERSHIP", "COUNT", "EXERCISE"),
]);
function evaluate(context: AnalyticsEvaluationContext): readonly MetricResult[] { const index = coreMetricIndex(context.debrief); const assignmentsByPatient = new Map<string, typeof index.assignmentEvents>(); for (const patient of context.debrief.patients) assignmentsByPatient.set(patient.patientId, Object.freeze(index.assignmentEvents.filter(event => event.patientId === patient.patientId))); const assignments = [...assignmentsByPatient.values()].flat(); const intervals: number[] = []; for (const events of assignmentsByPatient.values()) events.forEach((event, i) => intervals.push(Math.max(0, (events[i + 1]?.simulationTimeSec ?? context.debrief.simulationDurationSec) - event.simulationTimeSec))); const base = assignments.length ? eventEvidence(assignments) : [evidence("DEBRIEF_FIELD", "patients")]; const unavailable = (def: typeof defs[number], code: string, message: string) => unavailableResult(def, code, message, base); const durationUnavailable = legacyDuration(context) || !intervals.length; return Object.freeze([
  durationUnavailable ? unavailable(defs[0], legacyDuration(context) ? "LEGACY_EXERCISE_CLOCK" : "MISSING_OWNERSHIP_HISTORY", "Ownership duration is unavailable") : valueResult(defs[0], intervals.reduce((sum, value) => sum + value, 0) / intervals.length, base), durationUnavailable ? unavailable(defs[1], legacyDuration(context) ? "LEGACY_EXERCISE_CLOCK" : "MISSING_OWNERSHIP_HISTORY", "Ownership duration is unavailable") : valueResult(defs[1], Math.max(...intervals), base), durationUnavailable ? unavailable(defs[2], legacyDuration(context) ? "LEGACY_EXERCISE_CLOCK" : "MISSING_OWNERSHIP_HISTORY", "Ownership duration is unavailable") : valueResult(defs[2], Math.min(...intervals), base), valueResult(defs[3], [...assignmentsByPatient.values()].reduce((sum, events) => sum + Math.max(0, events.length - 1), 0), base), valueResult(defs[4], context.debrief.patients.filter(patient => patient.assignedCaseManagers.length === 0).length, [evidence("DEBRIEF_FIELD", "patients.assignedCaseManagers")]), unavailableResult(defs[5], "OWNERSHIP_INTERVALS_NOT_AVAILABLE", "Canonical overlap intervals are not available in Debrief", [evidence("DEBRIEF_FIELD", "patients.assignedCaseManagers")]),
]); }
export const OwnershipMetricsProvider: AnalyticsMetricProvider = Object.freeze({ providerId: id, version: "1.0.0", getDefinitions: () => defs, evaluate });

