import type { AssessmentMetricProvenance, AnalyticsEvaluationContext, AnalyticsMetricProvider, MetricDefinition, MetricEvidenceReference, MetricResult, MetricScope } from "@/models/analytics/Analytics";
import type { ProtocolAssessmentReport, ProtocolAssessmentResult, ProtocolAssessmentStatus } from "@/models/assessment/ProtocolAssessment";
import { comparePatientIds } from "@/services/runtime/selectors/InstructorDashboardSelector";

export const PROTOCOL_ASSESSMENT_METRICS_PROVIDER_ID = "assessment.protocol";
type MetricKey = "total" | "applicable" | "assessable" | "met" | "not_met" | "not_applicable" | "unavailable" | "completion_ratio" | "satisfaction_ratio";
const keys: readonly MetricKey[] = ["total", "applicable", "assessable", "met", "not_met", "not_applicable", "unavailable", "completion_ratio", "satisfaction_ratio"];
const names: Record<MetricKey, string> = { total: "Total expectations", applicable: "Applicable expectations", assessable: "Assessable expectations", met: "MET expectations", not_met: "NOT MET expectations", not_applicable: "Not applicable expectations", unavailable: "Unavailable expectations", completion_ratio: "Assessment completion ratio", satisfaction_ratio: "Expectation satisfaction ratio" };
const descriptions: Record<MetricKey, string> = { total: "All WP-38 assessment results", applicable: "MET, NOT_MET and UNAVAILABLE results", assessable: "MET and NOT_MET results", met: "Results with MET status", not_met: "Results with NOT_MET status", not_applicable: "Results excluded from applicable denominators", unavailable: "Applicable results lacking sufficient canonical evidence", completion_ratio: "Assessable divided by applicable expectations", satisfaction_ratio: "MET divided by assessable expectations; descriptive, not a score" };
const definition = (key: MetricKey, scope: MetricScope): MetricDefinition => Object.freeze({ metricId: scope === "EXERCISE" ? `assessment.expectations.${key}`.replace("expectations.completion_ratio", "completion_ratio").replace("expectations.satisfaction_ratio", "satisfaction_ratio") : `patient.assessment.${key}`, version: "1.0.0", name: names[key], description: descriptions[key], category: "ASSESSMENT", unit: key.endsWith("ratio") ? "RATIO" : "COUNT", scope, providerId: PROTOCOL_ASSESSMENT_METRICS_PROVIDER_ID, tags: Object.freeze(["assessment", "descriptive", "neutral"]) });
const definitions = Object.freeze(keys.flatMap(key => [definition(key, "EXERCISE"), definition(key, "PATIENT")]));
const byDefinition = new Map(definitions.map(item => [`${item.scope}:${item.metricId.split(".").at(-1)}`, item]));
const def = (key: MetricKey, scope: MetricScope) => byDefinition.get(`${scope}:${key}`)!;
const statuses = (results: readonly ProtocolAssessmentResult[], accepted: readonly ProtocolAssessmentStatus[]) => results.filter(result => accepted.includes(result.status));
const provenance = (report: ProtocolAssessmentReport): AssessmentMetricProvenance => Object.freeze({ protocolId: report.protocolId, protocolVersion: report.protocolVersion, protocolHash: report.protocolHash, assessmentVersion: report.assessmentVersion, assessmentHash: report.assessmentHash });
const evidence = (report: ProtocolAssessmentReport, results: readonly ProtocolAssessmentResult[]): readonly MetricEvidenceReference[] => Object.freeze([Object.freeze({ sourceType: "ASSESSMENT_REPORT" as const, sourceId: report.assessmentHash, fieldPath: "results" }), ...[...results].sort((a, b) => a.assessmentId.localeCompare(b.assessmentId)).map(result => Object.freeze({ sourceType: "ASSESSMENT_RESULT" as const, sourceId: result.assessmentId, patientId: result.patientId, fieldPath: `results[${result.expectationId}]` }))]);
const value = (report: ProtocolAssessmentReport, key: MetricKey, scope: MetricScope, amount: number, contributing: readonly ProtocolAssessmentResult[], subjectId?: string): MetricResult => Object.freeze({ metricId: def(key, scope).metricId, metricVersion: "1.0.0", providerId: PROTOCOL_ASSESSMENT_METRICS_PROVIDER_ID, scope, ...(subjectId ? { subjectId } : {}), category: "ASSESSMENT", status: "VALUE", value: amount, unit: key.endsWith("ratio") ? "RATIO" : "COUNT", evidence: evidence(report, contributing), assessmentProvenance: provenance(report) }) as MetricResult;
const notApplicable = (report: ProtocolAssessmentReport, key: MetricKey, scope: MetricScope, subjectId?: string): MetricResult => Object.freeze({ metricId: def(key, scope).metricId, metricVersion: "1.0.0", providerId: PROTOCOL_ASSESSMENT_METRICS_PROVIDER_ID, scope, ...(subjectId ? { subjectId } : {}), category: "ASSESSMENT", status: "NOT_APPLICABLE", reasonCode: "ZERO_DENOMINATOR", message: key === "completion_ratio" ? "No applicable expectations" : "No assessable expectations", unit: "RATIO", evidence: evidence(report, []), assessmentProvenance: provenance(report) });

export function aggregateAssessmentMetrics(report: ProtocolAssessmentReport, results: readonly ProtocolAssessmentResult[], scope: MetricScope, subjectId?: string): readonly MetricResult[] {
  const met = statuses(results, ["MET"]); const notMet = statuses(results, ["NOT_MET"]); const unavailable = statuses(results, ["UNAVAILABLE"]); const notApplicableResults = statuses(results, ["NOT_APPLICABLE"]); const applicable = [...met, ...notMet, ...unavailable]; const assessable = [...met, ...notMet];
  return Object.freeze([value(report, "total", scope, results.length, results, subjectId), value(report, "applicable", scope, applicable.length, applicable, subjectId), value(report, "assessable", scope, assessable.length, assessable, subjectId), value(report, "met", scope, met.length, met, subjectId), value(report, "not_met", scope, notMet.length, notMet, subjectId), value(report, "not_applicable", scope, notApplicableResults.length, notApplicableResults, subjectId), value(report, "unavailable", scope, unavailable.length, unavailable, subjectId), applicable.length ? value(report, "completion_ratio", scope, assessable.length / applicable.length, applicable, subjectId) : notApplicable(report, "completion_ratio", scope, subjectId), assessable.length ? value(report, "satisfaction_ratio", scope, met.length / assessable.length, assessable, subjectId) : notApplicable(report, "satisfaction_ratio", scope, subjectId)]);
}

export const ProtocolAssessmentMetricsProvider: AnalyticsMetricProvider = Object.freeze({ providerId: PROTOCOL_ASSESSMENT_METRICS_PROVIDER_ID, version: "1.0.0", allowEmptyScopes: Object.freeze(["PATIENT"] as const), getDefinitions: () => definitions, evaluate(context: AnalyticsEvaluationContext): readonly MetricResult[] { const report = context.protocolAssessment; if (!report) return Object.freeze([]); if (report.exerciseId !== context.exerciseId || !report.assessmentHash || !Object.isFrozen(report)) throw new Error("INVALID_PROTOCOL_ASSESSMENT_REPORT"); const patients = [...new Set(report.results.flatMap(result => result.patientId ? [result.patientId] : []))].sort(comparePatientIds); return Object.freeze([...aggregateAssessmentMetrics(report, report.results, "EXERCISE"), ...patients.flatMap(patientId => aggregateAssessmentMetrics(report, report.results.filter(result => result.patientId === patientId), "PATIENT", patientId))]); } });
