import type { AssessmentDiagnostic, AssessmentEvidenceReference, ProtocolAssessmentReport, ProtocolAssessmentResult } from "@/models/assessment/ProtocolAssessment";
import type { ClinicalProtocolConfiguration, ProtocolAssessmentExpectation } from "@/models/protocol/ClinicalProtocolConfiguration";
import type { ExerciseTimelineEvent } from "@/models/exercise/ExerciseTimelineEvent";
import type { DebriefReport } from "@/services/debrief/DebriefModel";
import { deepFreeze } from "@/utils/immutable"; import { sha256Text } from "@/utils/sha256"; import { stableJson } from "@/utils/stableJson";
import { actionMatches, conditionMatches, isConditionDomainEvidence } from "./AssessmentConditionEvaluator"; import { AssessmentEvidenceIndex } from "./AssessmentEvidenceIndex"; import { calculateAssessmentHash } from "./AssessmentHash"; import { evaluateTemporal } from "./AssessmentTemporalEvaluator";
const compare = (a: string, b: string) => a.localeCompare(b);
const evidenceType = (event: ExerciseTimelineEvent): AssessmentEvidenceReference["sourceType"] => event.type === "INTERVENTION" || event.type === "INTERVENTION_APPLIED" ? "INTERVENTION" : event.type === "MEDICATION" ? "MEDICATION" : /TRANSITION|RHYTHM|ROSC|CARDIAC/.test(event.type) ? "PATIENT_PROCESS" : "TIMELINE_EVENT";
const reference = (event: ExerciseTimelineEvent): AssessmentEvidenceReference => deepFreeze({ sourceType: evidenceType(event), sourceId: event.id, ...(event.patientId ? { patientId: event.patientId } : {}), simulationTimeSec: event.simulationTimeSec });
const diagnostic = (code: AssessmentDiagnostic["code"], message: string, expectationId: string, patientId?: string): AssessmentDiagnostic => deepFreeze({ code, message, expectationId, ...(patientId ? { patientId } : {}) });
const resultId = (protocolId: string, expectationId: string, patientId?: string) => `${protocolId}:${expectationId}:${patientId ?? "EXERCISE"}`;
export type ProtocolAssessmentContext = Readonly<{ protocol: ClinicalProtocolConfiguration; debrief: DebriefReport; timeline: readonly ExerciseTimelineEvent[] }>;
function evaluateExpectation(context: ProtocolAssessmentContext, index: AssessmentEvidenceIndex, expectation: ProtocolAssessmentExpectation, patientId?: string): ProtocolAssessmentResult {
  const base = { assessmentId: resultId(context.protocol.protocolId, expectation.expectationId, patientId), expectationId: expectation.expectationId, protocolId: context.protocol.protocolId, protocolVersion: context.protocol.version, ...(patientId ? { subjectId: patientId, patientId } : {}) };
  const knownRequirements = new Set(["TIMELINE", "INTERVENTION", "PATIENT_PROCESS_TRANSITION", "SIMULATION_TIME"]); const malformed = !expectation.expectationId.trim() || !expectation.expectedAction || !expectation.condition || expectation.temporalConstraint?.relation === "REPEATING" || expectation.evidenceRequirements.some(item => !knownRequirements.has(item));
  if (malformed) { const issue = diagnostic(expectation.temporalConstraint?.relation === "REPEATING" ? "INVALID_TEMPORAL_CONSTRAINT" : "INVALID_EXPECTATION", "Expectation cannot be evaluated by the WP-38 factual predicate set", expectation.expectationId, patientId); return deepFreeze({ ...base, status: "UNAVAILABLE", evidence: [], diagnostics: [issue] }); }
  const conditionKey = stableJson(expectation.condition); const triggers = index.select(`trigger:${conditionKey}`, patientId, event => conditionMatches(event, expectation.condition));
  if (!triggers.length) { const domainEvidence = index.select(`domain:${conditionKey}`, patientId, event => isConditionDomainEvidence(event, expectation.condition)); if (domainEvidence.length) return deepFreeze({ ...base, status: "NOT_APPLICABLE", evidence: domainEvidence.slice(0, 1).map(reference), diagnostics: [] }); const issue = diagnostic("MISSING_TRIGGER_EVIDENCE", "Canonical evidence does not establish whether the expectation applies", expectation.expectationId, patientId); return deepFreeze({ ...base, status: "UNAVAILABLE", evidence: [], diagnostics: [issue] }); }
  if (context.debrief.clockMigrationStatus !== "CANONICAL") { const issue = diagnostic("LEGACY_CLOCK", "Temporal assessment is unavailable because the exercise clock is not canonical", expectation.expectationId, patientId); return deepFreeze({ ...base, status: "UNAVAILABLE", evidence: [reference(triggers[0])], diagnostics: [issue] }); }
  const actions = index.select(`action:${expectation.expectedAction}`, patientId, event => actionMatches(event, expectation.expectedAction)); const trigger = triggers[0]; const candidates = actions.map(action => ({ action, temporal: evaluateTemporal(trigger, action, expectation.temporalConstraint) }));
  if (candidates.some(item => item.temporal.malformed)) { const issue = diagnostic("INVALID_TEMPORAL_CONSTRAINT", "Temporal constraint is malformed or unsupported", expectation.expectationId, patientId); return deepFreeze({ ...base, status: "UNAVAILABLE", evidence: [reference(trigger)], diagnostics: [issue] }); }
  const match = candidates.find(item => item.temporal.valid)?.action;
  if (match && expectation.evidenceRequirements.includes("PATIENT_PROCESS_TRANSITION")) { const transitions = index.select("patient-process-transition", patientId, event => /TRANSITION/.test(event.type) && event.simulationTimeSec >= match.simulationTimeSec); if (!transitions.length) { const issue = diagnostic("INCOMPLETE_DEBRIEF", "Required PatientProcess transition evidence is unavailable", expectation.expectationId, patientId); return deepFreeze({ ...base, status: "UNAVAILABLE", evidence: [reference(trigger), reference(match)], diagnostics: [issue] }); } return deepFreeze({ ...base, status: "MET", evidence: [reference(trigger), reference(match), reference(transitions[0])], diagnostics: [] }); }
  if (match) return deepFreeze({ ...base, status: "MET", evidence: [reference(trigger), reference(match)], diagnostics: [] });
  const issue = diagnostic("MISSING_ACTION_EVIDENCE", `No canonical ${expectation.expectedAction} evidence satisfies the expectation`, expectation.expectationId, patientId); return deepFreeze({ ...base, status: "NOT_MET", evidence: [reference(trigger), ...actions.slice(0, 1).map(reference)], diagnostics: [issue] });
}
/** Read-only evaluator: protocol expectations plus canonical Debrief/Timeline in, immutable report out. */
export function assessProtocol(context: ProtocolAssessmentContext): ProtocolAssessmentReport {
  if (!context.protocol?.protocolId || !context.debrief?.exerciseId || stableJson(context.timeline) !== stableJson(context.debrief.timeline)) throw new Error("INVALID_PROTOCOL_ASSESSMENT_CONTEXT");
  const index = new AssessmentEvidenceIndex(context.timeline); const patientIds = [...new Set(context.debrief.patients.map(patient => patient.patientId))].sort(compare); const results: ProtocolAssessmentResult[] = [];
  for (const expectation of [...context.protocol.assessmentExpectations].sort((a, b) => compare(a.expectationId, b.expectationId))) { const matchingPatients = patientIds.filter(patientId => index.events(patientId).some(event => isConditionDomainEvidence(event, expectation.condition))); const subjects: readonly (string | undefined)[] = matchingPatients.length ? matchingPatients : patientIds.length === 1 ? patientIds : [undefined]; for (const patientId of subjects) results.push(evaluateExpectation(context, index, expectation, patientId)); }
  results.sort((a, b) => compare(a.expectationId, b.expectationId) || compare(a.patientId ?? "", b.patientId ?? "") || compare(a.assessmentId, b.assessmentId)); const diagnostics = results.flatMap(result => result.diagnostics).sort((a, b) => compare(a.code, b.code) || compare(a.expectationId ?? "", b.expectationId ?? "") || compare(a.patientId ?? "", b.patientId ?? ""));
  const canonical = deepFreeze({ assessmentVersion: 1 as const, exerciseId: context.debrief.exerciseId, protocolId: context.protocol.protocolId, protocolVersion: context.protocol.version, protocolHash: context.protocol.protocolHash, sourceDebriefHash: sha256Text(stableJson(context.debrief)), results, diagnostics }); return deepFreeze({ ...canonical, assessmentHash: calculateAssessmentHash(canonical) });
}
