import type { ExerciseSession } from "@/models/ExerciseSession";
import type { CanonicalExerciseSnapshot } from "@/models/exercise/CanonicalExerciseSnapshot";
import type { ExerciseControlAuditEntry } from "@/models/exercise/ExerciseControlCommand";
import type { InstructorCommandAuditEntry } from "@/models/InstructorCommand";
import type { ImagingStudy } from "@/models/ImagingStudy";
import type { LabResult } from "@/models/LabResult";
import type { Note } from "@/models/Note";
import type { Order } from "@/models/Order";
import type { Patient } from "@/models/Patient";
import type { PatientAssignment } from "@/models/PatientAssignment";
import type { PatientTransfer } from "@/models/PatientTransfer";
import type { Question } from "@/models/Question";
import type { ScenarioEvent } from "@/models/ScenarioEvent";
import type { TimelineEvent } from "@/models/TimelineEvent";
import type { Intervention } from "@/models/Intervention";
import type { MedicationAdministration } from "@/models/Medication";
import type { VitalSigns } from "@/models/VitalSigns";
import type { PersistedRuntimeState } from "@/models/PersistedRuntimeState";
import type { MaterializedPatientDataset } from "@/models/exercise/PackagePatientDataset";
import type { InstalledWorkbook } from "@/services/WorkbookImportService";
import type { ExerciseResetAudit } from "@/services/runtime/exercise/ExerciseResetService";
import type { CompletedExerciseArchive } from "@/services/exercise/CompletedExerciseArchiveService";

export type SharedExerciseState = {
  exerciseSession: ExerciseSession | CanonicalExerciseSnapshot;
  patients: Patient[];
  assignments: PatientAssignment[];
  transfers: PatientTransfer[];
  questions: Question[];
  labs: LabResult[];
  imagingStudies: ImagingStudy[];
  orders: Order[];
  notes: Note[];
  scenarioEvents: ScenarioEvent[];
  timelineEvents: TimelineEvent[];
  interventions?: Intervention[];
  medicationAdministrations?: MedicationAdministration[];
  vitalSigns?: VitalSigns[];
  caseManagerZoneIds?: Record<string, string>;
  installedWorkbook?: InstalledWorkbook;
  exerciseControlAudit?: ExerciseControlAuditEntry[];
  instructorCommandAudit?: InstructorCommandAuditEntry[];
  exerciseResetAudit?: ExerciseResetAudit[];
  exercisePackageReference?: { packageId: string; packageVersion: string };
  completedExerciseArchives?: CompletedExerciseArchive[];
  patientMaterialization?: MaterializedPatientDataset;
  persistedRuntimeStates?: readonly PersistedRuntimeState[];
};
