import type { ExerciseTimelineCategory, ExerciseTimelineGroup, ExerciseTimelineSeverity } from "@/models/exercise/ExerciseTimelineEvent";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
const categories: readonly ExerciseTimelineCategory[] = ["EXERCISE", "PATIENT", "COMMAND", "SYSTEM", "AUDIT"];
const severities: readonly ExerciseTimelineSeverity[] = ["INFO", "WARNING", "ERROR"];
const groups: readonly ExerciseTimelineGroup[] = ["NONE", "TODAY", "SIMULATION_MINUTE", "PATIENT", "CATEGORY"];
export function ExerciseTimelineFilterBar(props: { categories: readonly ExerciseTimelineCategory[]; severities: readonly ExerciseTimelineSeverity[]; patientId: string; caseManager: string; search: string; grouping: ExerciseTimelineGroup; onCategories(value: ExerciseTimelineCategory[]): void; onSeverities(value: ExerciseTimelineSeverity[]): void; onPatientId(value: string): void; onCaseManager(value: string): void; onSearch(value: string): void; onGrouping(value: ExerciseTimelineGroup): void }) {
  const toggle = <T extends string>(items: readonly T[], value: T) => items.includes(value) ? items.filter(item => item !== value) : [...items, value];
  return <View style={styles.card}>
    <TextInput style={styles.input} value={props.search} onChangeText={props.onSearch} placeholder="Search timeline" />
    <View style={styles.inputs}><TextInput style={[styles.input, styles.flex]} value={props.patientId} onChangeText={props.onPatientId} placeholder="Patient ID" autoCapitalize="characters" /><TextInput style={[styles.input, styles.flex]} value={props.caseManager} onChangeText={props.onCaseManager} placeholder="Case Manager" /></View>
    <Text style={styles.label}>Category</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.row}>{categories.map(item => <Pressable key={item} style={[styles.chip, props.categories.includes(item) && styles.active]} onPress={() => props.onCategories(toggle(props.categories, item))}><Text style={[styles.chipText, props.categories.includes(item) && styles.activeText]}>{item}</Text></Pressable>)}</ScrollView>
    <Text style={styles.label}>Severity</Text><View style={styles.row}>{severities.map(item => <Pressable key={item} style={[styles.chip, props.severities.includes(item) && styles.active]} onPress={() => props.onSeverities(toggle(props.severities, item))}><Text style={[styles.chipText, props.severities.includes(item) && styles.activeText]}>{item}</Text></Pressable>)}</View>
    <Text style={styles.label}>Group</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.row}>{groups.map(item => <Pressable key={item} style={[styles.chip, props.grouping === item && styles.active]} onPress={() => props.onGrouping(item)}><Text style={[styles.chipText, props.grouping === item && styles.activeText]}>{item.replaceAll("_", " ")}</Text></Pressable>)}</ScrollView>
  </View>;
}
const styles = StyleSheet.create({ card: { backgroundColor: "#f4f5f7", borderRadius: 12, padding: 12, marginBottom: 14 }, input: { backgroundColor: "#fff", borderColor: "#b3bac5", borderWidth: 1, borderRadius: 9, paddingHorizontal: 11, paddingVertical: 9 }, inputs: { flexDirection: "row", gap: 8, marginTop: 8 }, flex: { flex: 1 }, label: { color: "#42526e", fontWeight: "800", fontSize: 12, marginTop: 10, marginBottom: 6 }, row: { flexDirection: "row", gap: 6 }, chip: { borderColor: "#8993a4", borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 }, active: { backgroundColor: "#005bbb", borderColor: "#005bbb" }, chipText: { color: "#42526e", fontSize: 11, fontWeight: "800" }, activeText: { color: "#fff" } });
