import type { ExercisePackage } from "@/models/exercise/ExercisePackage";
import type { ExercisePackageCompatibility } from "@/models/exercise/ExercisePackageManifest";
import { compatibilityLabel, exercisePackageNameLabel, exercisePackageTagLabel, exerciseProfileLabel, processStatusLabel } from "@/localization/et";
import { StyleSheet, Text, View } from "react-native";

export function ExercisePackageInformationCard({ exercisePackage, compatibility }: { exercisePackage: ExercisePackage; compatibility: ExercisePackageCompatibility }) {
  const protocol = exercisePackage.definition.protocolProvenance;
  const rows = [["Pakett", exercisePackageNameLabel(exercisePackage.metadata.name)], ["Versioon", exercisePackage.packageVersion], ["Profiil", exerciseProfileLabel(exercisePackage.definition.profile)], ["Autor", exercisePackage.metadata.author], ["Organisatsioon", exercisePackage.metadata.organization], ["Märksõnad", exercisePackage.metadata.tags.map(exercisePackageTagLabel).join(" · ")], ["Nõutavad moodulid", (exercisePackage.requiredClinicalModules ?? []).map(module => `${module.moduleId}@${module.version}`).join(" · ") || "Puudub"], ["Komponeeritud moodulid", (exercisePackage.definition.clinicalModuleComposition?.modules ?? []).map(module => `${module.moduleId}@${module.version}`).join(" · ") || "Puudub"], ...(protocol ? [["Protokoll", `${protocol.name} · ${protocol.protocolId}@${protocol.version}`], ["Protokolli olek", processStatusLabel(protocol.status)], ["Protokolli autoriteet", protocol.authority], ["Protokolli hash", protocol.protocolHash], ["Protokolli võimekused", protocol.requiredCapabilities.join(" · ")]] : []), ["Definitsioon", `${exercisePackage.definition.exerciseTypeId} v${exercisePackage.definition.definitionVersion}`], ["Ühilduvus", compatibilityLabel(compatibility)], ["Hash", exercisePackage.packageHash]];
  return <View style={styles.card} testID="exercise-package-information-card"><Text style={styles.title}>Õppusepaketi teave</Text>{rows.map(([label, value]) => <View key={label} style={styles.row}><Text style={styles.label}>{label}</Text><Text selectable={label === "Hash"} style={[styles.value, label === "Hash" && styles.hash]}>{value}</Text></View>)}</View>;
}
const styles = StyleSheet.create({ card: { borderWidth: 1, borderColor: "#c7d1de", backgroundColor: "#f7faff", borderRadius: 12, padding: 14, marginBottom: 12 }, title: { fontSize: 18, fontWeight: "900", color: "#172b4d", marginBottom: 3 }, row: { borderTopWidth: 1, borderTopColor: "#dfe7f0", paddingTop: 8, marginTop: 8 }, label: { color: "#6b778c", fontSize: 11, fontWeight: "800", textTransform: "uppercase" }, value: { color: "#172b4d", marginTop: 3, lineHeight: 19 }, hash: { fontFamily: "monospace", fontSize: 11 } });
