import type { TransportConfiguration } from "@/models/PatientTransport";
import { PatientTransportEngine } from "@/services/runtime/PatientTransportEngine";

const config: TransportConfiguration = { version: "1.0.0", vehicleLocationId: "REANIMOBILE", resources: [{ resourceId: "REANIMOBILE-01", resourceType: "CRITICAL_CARE_AMBULANCE", displayName: "Reanimobiil", capacity: 1, homeLocationId: "ED" }], destinations: [
  { destinationId: "THORACIC_CENTER", displayName: "Torakaalkeskus", capabilities: ["THORACOTOMY"], travelDurationSec: 1800, handoverDurationSec: 600, returnDurationSec: 1800, turnaroundDurationSec: 300 },
  { destinationId: "PELVIC_CENTER", displayName: "Vaagnatraumakeskus", capabilities: ["PELVIC_SURGERY"], travelDurationSec: 7200, handoverDurationSec: 600, returnDurationSec: 7200, turnaroundDurationSec: 0 },
] };
const engine = () => new PatientTransportEngine(config, { P01: "ED", P02: "ED" });

describe("WP-45C generic patient transport", () => {
  test("exclusive vehicle progresses through outbound, handover, return and turnaround", () => { const e=engine(); expect(e.start("C1","P01","REANIMOBILE-01","THORACIC_CENTER",0).status).toBe("STARTED"); let s=e.snapshot(); expect(s.patientLocations.P01).toBe("REANIMOBILE"); expect(s.resources[0].state).toBe("OUTBOUND"); expect(e.start("C2","P02","REANIMOBILE-01","THORACIC_CENTER",0)).toMatchObject({status:"REJECTED",reason:"TRANSPORT_RESOURCE_BUSY"}); e.advanceTo(1800); s=e.snapshot(); expect(s.patientLocations.P01).toBe("THORACIC_CENTER"); expect(s.resources[0].state).toBe("HANDOVER"); e.advanceTo(2400); expect(e.snapshot().resources[0]).toMatchObject({state:"RETURNING",currentPatientId:undefined}); expect(e.start("C3","P02","REANIMOBILE-01","THORACIC_CENTER",2400).reason).toBe("TRANSPORT_RESOURCE_BUSY"); e.advanceTo(4200); expect(e.snapshot().resources[0].state).toBe("TURNAROUND"); e.advanceTo(4500); expect(e.snapshot().resources[0].state).toBe("AVAILABLE"); expect(e.start("C4","P02","REANIMOBILE-01","THORACIC_CENTER",4500).status).toBe("STARTED"); });
  test("same command replay is idempotent and a new retry works", () => { const e=engine(); const first=e.start("C1","P01","REANIMOBILE-01","THORACIC_CENTER",0); expect(e.start("C1","P01","REANIMOBILE-01","THORACIC_CENTER",0)).toEqual(first); expect(e.snapshot().transports).toHaveLength(1); expect(e.snapshot().evidence).toHaveLength(3); expect(e.start("BUSY","P02","REANIMOBILE-01","THORACIC_CENTER",0).reason).toBe("TRANSPORT_RESOURCE_BUSY"); e.advanceTo(4500); expect(e.start("RETRY","P02","REANIMOBILE-01","THORACIC_CENTER",4500).status).toBe("STARTED"); });
  test("restart during outbound preserves identity, remaining time and location", () => { const a=engine(); a.start("C1","P01","REANIMOBILE-01","THORACIC_CENTER",0); a.advanceTo(600); const b=new PatientTransportEngine(config,{},a.snapshot()); expect(b.snapshot()).toMatchObject({currentSimulationTimeSec:600,patientLocations:{P01:"REANIMOBILE"}}); expect(b.snapshot().resources[0]).toMatchObject({state:"OUTBOUND",phaseEndsAtSec:1800}); b.advanceTo(1800); expect(b.snapshot().patientLocations.P01).toBe("THORACIC_CENTER"); });
  test("restart during return preserves unavailable resource", () => { const a=engine(); a.start("C1","P01","REANIMOBILE-01","THORACIC_CENTER",0); a.advanceTo(3000); const b=new PatientTransportEngine(config,{},a.snapshot()); expect(b.snapshot().resources[0]).toMatchObject({state:"RETURNING",phaseEndsAtSec:4200}); expect(b.start("C2","P02","REANIMOBILE-01","THORACIC_CENTER",3000).reason).toBe("TRANSPORT_RESOURCE_BUSY"); b.advanceTo(4500); expect(b.snapshot().resources[0].state).toBe("AVAILABLE"); });
  test("pelvic-first consequence is duration-driven, not a failure flag", () => { const e=engine(); expect(e.start("P","P01","REANIMOBILE-01","PELVIC_CENTER",0).status).toBe("STARTED"); e.advanceTo(7199); expect(e.snapshot().resources[0].state).toBe("OUTBOUND"); expect(e.start("T","P02","REANIMOBILE-01","THORACIC_CENTER",7199).reason).toBe("TRANSPORT_RESOURCE_BUSY"); expect(e.snapshot().transports[0].state).toBe("IN_TRANSIT"); });
  test("evidence is sparse and canonical", () => { const e=engine(); e.start("C1","P01","REANIMOBILE-01","THORACIC_CENTER",0); e.advanceTo(4500); expect(e.snapshot().evidence.map(x=>x.type)).toEqual(["TRANSPORT_REQUESTED","PATIENT_ONBOARD","TRANSPORT_DEPARTED","TRANSPORT_ARRIVED","TRANSPORT_HANDOVER_COMPLETED","TRANSPORT_RETURNING","TRANSPORT_RESOURCE_AVAILABLE"]); });
  test("invalid references fail closed and do not mutate state", () => { const e=engine(); expect(e.start("A","P01","NOPE","THORACIC_CENTER",0).reason).toBe("UNKNOWN_RESOURCE"); expect(e.start("B","P01","REANIMOBILE-01","NOPE",0).reason).toBe("UNKNOWN_DESTINATION"); expect(e.start("C","P99","REANIMOBILE-01","THORACIC_CENTER",0).reason).toBe("INVALID_PATIENT_LOCATION"); expect(e.snapshot().transports).toHaveLength(0); });
  test("snapshot is deterministic and configuration mismatch is rejected", () => { const a=engine(); a.start("C1","P01","REANIMOBILE-01","THORACIC_CENTER",0); const state=a.snapshot(); expect(new PatientTransportEngine(config,{},state).snapshot()).toEqual(state); expect(()=>new PatientTransportEngine({...config,version:"2.0.0"},{},state)).toThrow("TRANSPORT_CONFIGURATION_MISMATCH"); });
});
